### ISSUE TITLE
Do we want to use css-in-js in this project?

### ISSUE THREAD

**Issue by taras** [thefrontside/frontside.com#55]
We're using it on our other projects. It feels kinda nice to not have to worry about globaliness of CSS. Should we start using something like `styled-components`?

**Comment by jbolda** [comment]
This is becoming a greater consideration in concert with https://github.com/thefrontside/frontside.com/issues/99#issuecomment-853399846.

**Comment by jorgelainfiesta** [comment]
We now use `vanilla-extract`
