### ISSUE TITLE
Broken img links on the blog

### ISSUE THREAD

**Issue by jorgelainfiesta** [thefrontside/frontside.com#74]
## Issue

A fellow reader sent us a message reporting that an article from 2016 had broken image links. 

It seems that the problem lays on how markdown is parsed after #69. When it encounters a `img` tag, the engine prepends a path all the way to `static` for that `src`. The same doesn't happen if we declare the image with markdown. 

## Solution

There's two alternatives:
- We either update replace all `img` tags on 6 articles from 2016-2017 for markdown images (30 instances).
- We debug the markdown mechanism to change its behavior.

**Comment by jorgelainfiesta** [comment]
Submitted a quick fix on #73 to address the article of interest.

**Comment by minkimcello** [comment]
@jorgelainfiesta can i close this?
