### ISSUE TITLE
Improve the process to import Webflow pages

### ISSUE THREAD

**Issue by jorgelainfiesta** [thefrontside/frontside.com#99]
## Motivation 

Right now we need to make several manual changes to the files generated by webflow to make them work alongside the Gatsby website.

## Approach

We can write a small script that applies the transforms to the webflow pages for us. There's probably other alternatives that may be nice too.

**Comment by jbolda** [comment]
I discussed with Jorge today about the current status of webflow. I think we are going to move these pages into the gatsby site in an incremental way, but in the process, we probably want to get some mindshare around which form our css should take. It seems to make sense to use the same system across all of our sites if reasonable.

@jorgelainfiesta and @cherewaty have any opinions about this?

**Comment by jbolda** [comment]
Importing new or re-importing existing pages is still painful, but viewing them has been improved in #140.

**Comment by jorgelainfiesta** [comment]
We no longer use webflow
